### ISSUE TITLE
Name or service not known

### ISSUE THREAD

**Issue by rageshns** [fod-dev/FoDBugTrackerUtility#24]
[main] [Process] Error during process run for submitVulnerabilitiesAndUpdateIssueState: java.net.UnknownHostException: http: Name or service not known
javax.ws.rs.ProcessingException: java.net.UnknownHostException: http: Name or service not known
	at com.fortify.util.rest.connector.ApacheConnector.apply(ApacheConnector.java:500) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.util.rest.RestConnection.executeRequest(RestConnection.java:185) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.util.rest.RestConnection.executeRequest(RestConnection.java:168) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.jira.connection.JiraRestConnection.submitIssue(JiraRestConnection.java:60) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.jira.processor.ProcessorJiraSubmitIssueForVulnerabilities.submitIssue(ProcessorJiraSubmitIssueForVulnerabilities.java:66) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.common.processor.AbstractProcessorSubmitIssueForVulnerabilities.processMap(AbstractProcessorSubmitIssueForVulnerabilities.java:93) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessorBuildObjectMapFromGroupedObjects.processGroup(AbstractProcessorBuildObjectMapFromGroupedObjects.java:70) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessorGroupByExpressions.postProcess(AbstractProcessorGroupByExpressions.java:168) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:101) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:81) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractCompositeProcessor.processForAll(AbstractCompositeProcessor.java:113) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractCompositeProcessor.postProcess(AbstractCompositeProcessor.java:95) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:101) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:81) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.fod.processor.retrieve.FoDProcessorRetrieveVulnerabilities.process(FoDProcessorRetrieveVulnerabilities.java:128) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:100) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:81) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractCompositeProcessor.processForAll(AbstractCompositeProcessor.java:113) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractCompositeProcessor.process(AbstractCompositeProcessor.java:86) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor._process(AbstractProcessor.java:100) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.processor.AbstractProcessor.process(AbstractProcessor.java:81) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.ProcessRunner.process(ProcessRunner.java:89) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.ProcessRunner.run(ProcessRunner.java:73) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.run(RunProcessRunnerFromSpringConfig.java:86) [FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromCLI.runProcessRunner(RunProcessRunnerFromCLI.java:111) [FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromCLI.main(RunProcessRunnerFromCLI.java:323) [FortifyBugTrackerUtility-3.1.jar:?]
Caused by: java.net.UnknownHostException: http: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[?:1.8.0_131]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[?:1.8.0_131]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[?:1.8.0_131]
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276) ~[?:1.8.0_131]
	at java.net.InetAddress.getAllByName(InetAddress.java:1192) ~[?:1.8.0_131]
	at java.net.InetAddress.getAllByName(InetAddress.java:1126) ~[?:1.8.0_131]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71) ~[FortifyBugTrackerUtility-3.1.jar:?]
	at com.fortify.util.rest.connector.ApacheConnector.apply(ApacheConnector.java:454) ~[FortifyBugTrackerUtility-3.1.jar:?]
	... 33 more

**Comment by rsenden** [comment]
This is probably caused by the FoD domain name changes. Please try with the latest available version that can be built from source here: https://github.com/fod-dev/FoDBugTrackerUtility/tree/processrunner-bugtracker-root-3.3, and make sure that you are using the new FoD DNS names.
